### ISSUE TITLE
what license is it going to be?

### ISSUE THREAD

**Issue by franzenzenhofer** [liip/barcode.js#1]
hi, i would love to integrate a working barcode scanner into https://github.com/franzenzenhofer/miniqr

is the license going to be MIT compatible? 
and if yes, does it work, yet? (didn't work with the bit.ly/TFGsOf yet) 

thx for your time

**Comment by fabian** [comment]
Hi Franz,

I've added the license (MIT). So far it only works with EAN13 barcodes.

Greetings,
Fabian
